### ISSUE TITLE
校对 FDL 时，不要删除英文原文！

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/fsfs-zh#70]
因为此书是 FDL 许可的，所以需要附加一份英文原版的 FDL 文本。所以这里就不删除原文了。

**Comment by Artoria2e5** [comment]
感觉现在第 X 款这样有严重得呈现与内容分离失败问题……理想的话是这么实现：

```Markdown
<span class="subnode-ol-type-hans-article">
1. blah
2. blah
3. blah
</span>
```

```CSS
@counter-style simp-chinese-informal-article {
  system: extends simp-chinese-informal-article;
  prefix: "第";
  suffix: "款";
}

.subnode-ol-type-hans-article > ol > li {
  list-style-type: simp-chinese-informal-article;
}
```
